config/routes.rb
Rails.application.routes.draw do

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :organization, only: [:show] # opt. :edit, :update

  namespace :organization, module: :organizations do
    resources :users, only: [:new, :create]
  end

  resources :projects, only: [:show, :new, :create] do # opt. :index, :edit, :update // :destroy
    resources :tests, only: [:show, :new, :create, :edit, :update, :destroy]
  end
# .opt
# resource :profile, only: [:show, :edit, :update]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :tests, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.includes(tests: :results).find(params[:id])

    tests = @project.tests.group_by do |test|
      result = test.results.sort_by(&:created_at).reverse.first

      if result
        result.correct ? :correct : :incorrect
      else
        :no_results_yet
      end
    end

    @incorrect_tests = tests[:incorrect]
    @correct_tests = tests[:correct]
    @no_results_tests = tests[:no_results_yet]
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.organization = current_user.organization

    @project.save
    redirect_to project_path(@project)
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/new.html.erb
  <%= link_to "back", organization_path %>
<div class="container">


  <h1>New project!</h1>

  <%= simple_form_for(@project) do |f| %>
    <%= f.input :name, placeholder: 'Campaign', :label => "What's the name of your project?" %>

    <%= f.button :submit, 'new project', class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container" id="project-container">
  <div class="container-title">
    <h1><%= @project.name %> </h1>
      <%= link_to 'New test', new_project_test_path(@project), class:'btn btn-primary' %>
  </div>

    <h4 class="test-link"> <%= link_to 'Back to organization', organization_path%>  </h4>



    <div class="project-cards">

    <% if @incorrect_tests.present? %>
      <% @incorrect_tests.each do |test| %>
        <%= link_to project_test_path(@project, test) do %>
          <div class="project-card">
              <% if test.name.length >= 19  %>
                <h5><%= test.name.slice(0, 19) %>[...]</h5>
              <% else %>
                <h5><%= test.name %></h5>
              <% end %>
              <p><i class="far fa-calendar-alt"></i> <%= test.updated_at.strftime"%d %B %Y at %H:%M" %></p>
              <div class="correct">
                <i class="far fa-times-circle"></i>
              </div>
              <button class="btn btn-primary">See report</button>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <% if @correct_tests.present? %>
      <% @correct_tests.each do |test| %>
        <%= link_to project_test_path(@project, test) do %>
          <div class="project-card">
            <% if test.name.length >= 19  %>
              <h5><%= test.name.slice(0, 19) %>[...]</h5>
            <% else %>
              <h5><%= test.name %></h5>
            <% end %>
            <p><i class="far fa-calendar-alt"></i> <%= test.updated_at.strftime"%d %B %Y at %H:%M" %></p>
            <div>
            <i class="far fa-check-circle"></i>
            </div>
            <button class="btn btn-primary">See report</button>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <% if @no_results_tests.present? %>
      <% @no_results_tests.each do |test| %>
        <div class="project-card">
          <% if test.name.length >= 25  %>
            <h5><%= test.name.slice(0, 25) %>[...]</h5>
          <% else %>
            <h5><%= test.name %></h5>
          <% end %>
          <p>Waiting for first test!</p>
          <div>
          <i class="fas fa-history"></i>
          </div>
        </div>
      <% end %>
    <% end %>

    </div>
  </div>