config/routes.rb
Rails.application.routes.draw do

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :organization, only: [:show] # opt. :edit, :update

  namespace :organization, module: :organizations do
    resources :users, only: [:new, :create]
  end

  resources :projects, only: [:show, :new, :create] do # opt. :index, :edit, :update // :destroy
    resources :tests, only: [:show, :new, :create, :edit, :update, :destroy]
  end
# .opt
# resource :profile, only: [:show, :edit, :update]
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :projects, dependent: :destroy
  has_many :users
end

app/controllers/organizations/users_controller.rb
class Organizations::UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = current_user.organization.users.new(user_params)
    @user.organization = current_user.organization

    if @user.save
      redirect_to organization_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def show
    @organization = current_user.organization
    @users = current_user.organization.users
    @projects = current_user.projects
  end
end

app/views/organizations/show.html.erb
<div class="container" id="orga-container">

  <div id='orga-admin-infos'>
    <div class="orga-credits-monthly">
      <div class="orga-big-number">150</div>
      <div>Credits/month</div>
    </div>

    <div class="orga-credits-left">
      <div class="orga-big-number"><%= @organization.current_credits %></div>
      <div>Credit(s) left</div>
      <button type="button" class="btn btn-info orga-cta">Extra credits</button>
    </div>

    <div class="orga-users">
      <div class="orga-big-number"><%= @organization.users.count %></div>
      <div>user(s)</div>
      <button type="button" class="btn btn-info orga-cta">Manage users</button>
    </div>
  </div>

  <h2 class="orga-section-bar">Credit consumption history</h2>

  <canvas
  class="graph"
  id="chart-line"
  >
  </canvas>

  <div class="orga-section-bar">
    <h2>Projects overview</h2>
    <%= link_to "Create a project", new_project_path, class: "btn btn-primary"  %>
  </div>

  <div id="orga-projects-grid">
    <% @projects.each do |project| %>
      <% tests_with_results = project.tests.select {|test| !test.results.empty? } %>
      <div class="orga-project-card">
        <div class="orga-project-card-header">
          <div class="orga-project-card-header-title">
            <div>
              <h4><strong><%= project.name %></strong></h4>
              <div class="orga-tests-running"><%= project.tests.count %> test(s) running</div>
            </div>


            <%= link_to(project_path(project)) do %>
              <i class="fas fa-eye orga-link-project"></i>
            <% end %>

          </div>
        </div>
        <div class="orga-project-card-body">
          <span class="error-number"> <strong> <%=  error = tests_with_results.map {|test| test.results.last.number_incorrect_values }.sum %></span></strong> errors on last run</div>
      </div>
    <% end %>
  </div>

</div>